onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - netlify-cli
  - unrs-resolver

overrides:
  diff@>=4.0.0 <4.0.4: '>=4.0.4'
  h3@<=1.15.4: '>=1.15.5'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.0.11: '>=16.0.11'
  next@>=16.0.0-beta.0 <16.1.5: '>=16.1.5'
  qs@<6.14.1: '>=6.14.1'
  storybook@>=10.0.0 <10.1.10: '>=10.1.10'
  tar@<7.5.7: '>=7.5.7'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
