import { notoSans, notoSansJP, notoSansKR } from '@/shared/config/font';
import Footer from '@/widgets/footer';
import Header from '@/widgets/header';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyClasses = `${notoSans.variable} ${notoSansKR.variable} ${notoSansJP.variable} antialiased`;
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={bodyClasses}>
        <div className="min-h-screen text-gray-900">
          <Header />
          <main className="mx-auto max-w-4xl px-6 py-10">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
