/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './../../pages/__root'
import { Route as LoginRouteImport } from './../../pages/login'
import { Route as ContactRouteImport } from './../../pages/contact'
import { Route as IndexRouteImport } from './../../pages/index'
import { Route as TagsIndexRouteImport } from './../../pages/tags/index'
import { Route as PostsIndexRouteImport } from './../../pages/posts/index'
import { Route as AdminIndexRouteImport } from './../../pages/admin/index'
import { Route as AboutIndexRouteImport } from './../../pages/about/index'
import { Route as TagsTagNameRouteImport } from './../../pages/tags/$tagName'
import { Route as PostsSlugRouteImport } from './../../pages/posts/$slug'
import { Route as AdminWriteRouteImport } from './../../pages/admin/write'
import { Route as AdminSettingsRouteImport } from './../../pages/admin/settings'
import { Route as AdminManageRouteImport } from './../../pages/admin/manage'
import { Route as AdminLayoutRouteImport } from './../../pages/admin/_layout'
import { Route as AboutResumeRouteImport } from './../../pages/about/resume'

const AdminRouteImport = createFileRoute('/admin')()

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsIndexRoute = TagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagNameRoute = TagsTagNameRouteImport.update({
  id: '/tags/$tagName',
  path: '/tags/$tagName',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWriteRoute = AdminWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageRoute = AdminManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)
const AboutResumeRoute = AboutResumeRouteImport.update({
  id: '/about/resume',
  path: '/about/resume',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/about/resume': typeof AboutResumeRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/write': typeof AdminWriteRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tags/$tagName': typeof TagsTagNameRoute
  '/about': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/posts': typeof PostsIndexRoute
  '/tags': typeof TagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/about/resume': typeof AboutResumeRoute
  '/admin': typeof AdminIndexRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/write': typeof AdminWriteRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tags/$tagName': typeof TagsTagNameRoute
  '/about': typeof AboutIndexRoute
  '/posts': typeof PostsIndexRoute
  '/tags': typeof TagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/about/resume': typeof AboutResumeRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/manage': typeof AdminManageRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/write': typeof AdminWriteRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/tags/$tagName': typeof TagsTagNameRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/tags/': typeof TagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/login'
    | '/about/resume'
    | '/admin'
    | '/admin/manage'
    | '/admin/settings'
    | '/admin/write'
    | '/posts/$slug'
    | '/tags/$tagName'
    | '/about'
    | '/admin/'
    | '/posts'
    | '/tags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/about/resume'
    | '/admin'
    | '/admin/manage'
    | '/admin/settings'
    | '/admin/write'
    | '/posts/$slug'
    | '/tags/$tagName'
    | '/about'
    | '/posts'
    | '/tags'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/login'
    | '/about/resume'
    | '/admin'
    | '/admin/_layout'
    | '/admin/manage'
    | '/admin/settings'
    | '/admin/write'
    | '/posts/$slug'
    | '/tags/$tagName'
    | '/about/'
    | '/admin/'
    | '/posts/'
    | '/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  AboutResumeRoute: typeof AboutResumeRoute
  AdminRoute: typeof AdminRouteWithChildren
  PostsSlugRoute: typeof PostsSlugRoute
  TagsTagNameRoute: typeof TagsTagNameRoute
  AboutIndexRoute: typeof AboutIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  TagsIndexRoute: typeof TagsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/': {
      id: '/tags/'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tagName': {
      id: '/tags/$tagName'
      path: '/tags/$tagName'
      fullPath: '/tags/$tagName'
      preLoaderRoute: typeof TagsTagNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/write': {
      id: '/admin/write'
      path: '/write'
      fullPath: '/admin/write'
      preLoaderRoute: typeof AdminWriteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage': {
      id: '/admin/manage'
      path: '/manage'
      fullPath: '/admin/manage'
      preLoaderRoute: typeof AdminManageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/about/resume': {
      id: '/about/resume'
      path: '/about/resume'
      fullPath: '/about/resume'
      preLoaderRoute: typeof AboutResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminManageRoute: typeof AdminManageRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminWriteRoute: typeof AdminWriteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLayoutRoute: AdminLayoutRoute,
  AdminManageRoute: AdminManageRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminWriteRoute: AdminWriteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  AboutResumeRoute: AboutResumeRoute,
  AdminRoute: AdminRouteWithChildren,
  PostsSlugRoute: PostsSlugRoute,
  TagsTagNameRoute: TagsTagNameRoute,
  AboutIndexRoute: AboutIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  TagsIndexRoute: TagsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
